#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
// Run the console kernel using a proper Console Input object so
// modern Symfony/Illuminate Console signatures are satisfied.
$kernel = new Laravel\Lumen\Console\Kernel($app);
$input = new Symfony\Component\Console\Input\ArgvInput();
$kernel->handle($input);
